// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// ProduceExchange provides a mock function with given fields: exchangeName, data
func (_m *Producer) ProduceExchange(exchangeName string, data interface{}) error {
	ret := _m.Called(exchangeName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(exchangeName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProduceQueue provides a mock function with given fields: queueName, data
func (_m *Producer) ProduceQueue(queueName string, data interface{}) error {
	ret := _m.Called(queueName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(queueName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
